### ISSUE TITLE
not able to control font size

### ISSUE THREAD

**Issue by kajapanisrikanth** [mediassarQlikBranch/SimpleFieldSelect#11]
Hello,
i'm trying to control the font size for check box option.
i tried different option in Appearance --> Other Visual Tab but nothing seems to work.
is there a option to control the font size for the values?

**Comment by mediassarQlikBranch** [comment]
You can use Advanced CSS & HTML section and "Custom font css string". Use for example: 
1.6em  sans-serif;

https://developer.mozilla.org/en-US/docs/Web/CSS/font

Double quota is not allowed! Input verification will be added later.

**Comment by kajapanisrikanth** [comment]
Hello Matti,

I tried to use the same example below but it doesn’t seems work.
Appreciate if you can provide some insights where I’m going wrong.
> 1.6em sans-serif;
> 

Thanks,
Phani Kaja

**Comment by mediassarQlikBranch** [comment]
Hi

could you send screenshot from this particular setting? And please send it by email. I hope you can resolve my email address so I don't have to post it here. Use for example my firstname and then mediassar.fi as the domain.

Matti

**Comment by shokyee** [comment]
Hi, I having the similar issue which is about the test alignment .
I have tried with place below statement:-
text-align: center;
but it seems not working
Place it under Texts tab; Label text CSS
