### ISSUE TITLE
Internal error // selecting dropdown headline/title

### ISSUE THREAD

**Issue by tom3187** [mediassarQlikBranch/SimpleFieldSelect#13]
You will get an "internal error" in combination with the following scenario:
Configuration:
- Dropdown (select2) restricted to only one selection

Scenario:
1. Select a default filter
2. Change the filter back to the "filter headline/title"
3. Internal error is thrown...

The Problem is, that with the "self.backendApi.selectValues" function it's not possible to clear a filter without any new filter Element ...

Attached you will find a fix...
Line: 150 - 154
and 
1477
and 
1482
[SimpleFieldSelect.txt](https://github.com/mediassarQlikBranch/SimpleFieldSelect/files/3028557/SimpleFieldSelect.txt)

**Comment by mediassarQlikBranch** [comment]
Thanks for the contribution! I'm not able to reproduce the issue, maybe my Qlik Sense is newer or something. Anyway I implemented NaN value handling. Special list clear is not needed in my opinion, it should work with empty array [].
