### ISSUE TITLE
select2 dropdown CSS changes

### ISSUE THREAD

**Issue by hvdbunte** [mediassarQlikBranch/SimpleFieldSelect#14]
Hi,

Thanks for this great Qlik extension. We still have an issue with styling the select2 dropdown box. We would like to change the color of the selection bar. By default it is blue. We changed it to pink in the select2.css. 

`
.select2-results__option--highlighted[aria-selected] {
  background-color: #EF145A;
  color: white; }
`

But would it be possible to add this code in the advanced section of the extension? And if so how can I make the proper modifications. Because I have little to no experience with HTML/CSS. 
Thanks,

Hendri

**Comment by mediassarQlikBranch** [comment]
Hi,
There will be simple options for this in 1.9.12 version. Thanks for the idea.
