### ISSUE TITLE
Dropdown limited to 1000 rows

### ISSUE THREAD

**Issue by lweitzel** [mediassarQlikBranch/SimpleFieldSelect#17]
It seems the dropdowns only show the first 1,000 rows.   Is there a way to increase this?

**Comment by DBALICKI** [comment]
Any chance a solution was found for this?

**Comment by mediassarQlikBranch** [comment]
Are you using old version of the extension? Some old one had this limitation with all visualizations. 
I tested with several thousands of items and both dropdowns worked.
