### ISSUE TITLE
Text Alignment unable perform as it is

### ISSUE THREAD

**Issue by shokyee** [mediassarQlikBranch/SimpleFieldSelect#18]
Hi didn't know your email so via here by raise an issues hope you could reply here.
After reading one of the issue about the font size, hereby I raise my issue as well which is about the text alignment .
The visualization I pick is "Qlik Switch" (as picture attach below)
![image](https://user-images.githubusercontent.com/41567134/64767608-8ecc7080-d57a-11e9-8bcc-43eb34fa2558.png)
I pick the text horizontal align to center (as picture attach below)
![image](https://user-images.githubusercontent.com/41567134/64767665-a3106d80-d57a-11e9-93b0-a546a6148cd5.png)
When I try to have allow the layout of extension become rectangle, I expect it will align the text to center which it do not perform the allignment.

Please let us know where or how I could do in order to allow the text align center

Thank you

**Comment by mediassarQlikBranch** [comment]
Hello!
Unfortuately due to the implementation of this Qlik Native switch I didn't find easy way to achieve the result you requested. The horizontal text align doesn't have effect on this Visualization. Sorry about that!

**Comment by shokyee** [comment]
Hi Matti,

If unable to achieve it in an easy way, is there any workaround or direct
into which script file we can do the changes?

Appreciate if you can answer.

Thank you

Regards
Shokyee

**Comment by mediassarQlikBranch** [comment]
Hi
so you would like to center the text horizontally, next to switches on the space there is available? Am I right?

Matti

Lähettäjä: shokyee [mailto:notifications@github.com]
Lähetetty: tiistai 17. syyskuuta 2019 7.00
Vastaanottaja: mediassarQlikBranch/SimpleFieldSelect
Kopio: Matti Punkeri; State change
Aihe: Re: [mediassarQlikBranch/SimpleFieldSelect] Text Alignment unable perform as it is (#18)

Hi Matti,

If unable to achieve it in an easy way, is there any workaround or direct
into which script file we can do the changes?

Appreciate if you can answer.

Thank you

Regards
Shokyee

**Comment by shokyee** [comment]
Hi Matti,

Yes.
