### ISSUE TITLE
Feature suggestion: Searching for list of entries in specific field(s)

### ISSUE THREAD

**Issue by mountaindude** [mediassarQlikBranch/SimpleFieldSelect#19]
A very useful QlikView feature is the possibility to paste a (potentially long) list of values, and search for those values in a specific field. 
In Sense, botth the global smart search and the search within list boxes is limited to 255 characters, which quickly becomes a limiting factor. 

Would be great to have an extension in which you could past a list of say 3000 values, which will be matched against one or more fields in the Sense app. 
Looking at the various Sense APIs, there is no mention of a limit to how large search arrays you can send in, so maybe it's possible... Some frontend/HTML + Javascript to access the APIs needed, for sure - but maybe doable..

**Comment by mediassarQlikBranch** [comment]
This kind of feature is now implemented with version 1.9.21. Check search options. You have to define separator field which is used between values. I didn't test with 3000 values, but try it!
