### ISSUE TITLE
issue after qlik upgrade from sept 2018 to april 2019

### ISSUE THREAD

**Issue by hvdbunte** [mediassarQlikBranch/SimpleFieldSelect#20]
Hi,

We just upgraded from sept 2018 sp4 to april 2019 sp3. But now we have an issue with opening some apps.
We created a master visualization for disabling the center part of the main toolbar. But I am not able to remove the visualization anymore, there is no delete option when I click with my right mouse button.  And it doesn’t open correctly in an Iframe. 

See screenshots for the issue. I only see this happening when using the master item. I also lost the name of the master 
 visualization. 
Any idea how I can resolve this?

Thanks for your help

![screenshot1_default state](https://user-images.githubusercontent.com/16244611/67812042-63f09a00-fa9e-11e9-9893-7e63aca5095f.jpg)
![screenshot2_default state](https://user-images.githubusercontent.com/16244611/67812045-67842100-fa9e-11e9-8d8d-39384d38801f.jpg)

**Comment by mediassarQlikBranch** [comment]
I think this is Qlik related. Your screenshosts are from Alternate states, not Visualization part of the master items. Check the Visualization!
