### ISSUE TITLE
Hide whole main toolbar not working

### ISSUE THREAD

**Issue by imtiazu** [mediassarQlikBranch/SimpleFieldSelect#25]
Hi there, 

Seems like the Hide whole main toolbar no longer works. I'm using Qlik Sense Ent. Nov 19 release.
The bar is always displayed even when set to hide.

Thanks
Immy

**Comment by mediassarQlikBranch** [comment]
I tested with Nov 19 SP2, and it works. It requires page refresh after hide has been enabled.
Info text added about refresh to 1.9.28 release. Please reopen if this doesn't help.

**Comment by imtiazu** [comment]
Have checked further and found it was conflicting with another extension. Thanks.
