### ISSUE TITLE
Header font size

### ISSUE THREAD

**Issue by EugeneZide** [mediassarQlikBranch/SimpleFieldSelect#27]
Hello, can I ask for subj ?
Thank in advance, Eugene

**Comment by mediassarQlikBranch** [comment]
Hi, sorry, I'm not following. What do you mean by subj? For objects own header or label CSS can be used, field "Label text CSS". Or do you mean font size of the global options header...

**Comment by EugeneZide** [comment]
![simple_header](https://user-images.githubusercontent.com/58972038/75649945-9f29f200-5c65-11ea-94a6-c1c8f9b68321.jpg)

Hi, i'm attached a file. When using both your extension and standart QS filter, i have this. Name of filter in your addon is same size as _common_ name of QS filter, but name of _elements_ of QS filter is smaller. So, as long as i don't need _common_ name of QS filter, on my page i have extension header bigger, then elements of QS filter.

btw, i drop my asking. thank for answer.
