### ISSUE TITLE
Error when 2 'Only search and select' visualisations used

### ISSUE THREAD

**Issue by TFletchuk** [mediassarQlikBranch/SimpleFieldSelect#29]
Great extension by the way.

I'd like to use the 'Only search and select' visualisation to allow users to search both forenames and surnames (or more) but when I add two instances and apply two searches I get an error:

"An error has occured. Invalid parameters"

Or it gives obscure results but single searches work fine.

In essence it would be great if it could provide a very clean an efficient wild card text search that allows multiple instances so that multiple columns can be filtered simultaneously without the multi select appearing as it does with the standard 'Filter Pane'. 

Is this a known issue or is there a workaround?

It would also be great to be able to hide the 'Clear search' X as it appears on top of the row results count when the search box is set to just one row.

Thanks

**Comment by mediassarQlikBranch** [comment]
Hi, thanks for pointing out this issue. Problem with two or more search only instances on one sheet is now fixed in version 1.9.31
Hide clear button option will be in next release.

**Comment by TFletchuk** [comment]
Brilliant.

Many thanks
