### ISSUE TITLE
Selection in Horizontal Qlik Sense list is not taking the first element when dragging with mouse

### ISSUE THREAD

**Issue by miguki** [mediassarQlikBranch/SimpleFieldSelect#30]
Firstly I would like to thank you for this wonderful extension!

There is an issue when you try to select multiple elements with mouse drag the first element that is clicked is not being selected. Please have a look on attached video.

Tested with version 1.9.31 on Qlik Sense February 2020 and 2.0.0 with April 2020

[skip year.zip](https://github.com/mediassarQlikBranch/SimpleFieldSelect/files/4461547/skip.year.zip)

**Comment by miguki** [comment]
Hello, any feedback?

**Comment by mediassarQlikBranch** [comment]
This is known "feature" which I tried to fix when I developed the feature. After several hours with no luck I did gave up. I'll give it a try later!
