### ISSUE TITLE
Scrollbar in QlikSense Feb 2020 SR1 (Mobile)

### ISSUE THREAD

**Issue by giulioborra** [mediassarQlikBranch/SimpleFieldSelect#32]
Thanks for keeping this extensions updated (especially on the "Disable Zoom effect" on Mobile).

I am finding issues on the mobile scrollbar (Qlik Sense feb 2020 SR1). I cannot scroll anymore vertically after the upgrade. Is it a known issue? 

Kind regards,
GB

**Comment by giulioborra** [comment]
FYI, I temporarily resolved by adding the _Overflow-y_ in _.qv-object-SimpleFieldSelect .sfs_lui_ (into the SimpleFieldStyle.css file)

**Comment by mediassarQlikBranch** [comment]
It is now fixed with 2.0.11 version. Sorry for the delay!
