### ISSUE TITLE
Size of Element height(Mobile view through the browser)

### ISSUE THREAD

**Issue by GGrodzki** [mediassarQlikBranch/SimpleFieldSelect#34]
Thanks for keeping this extensions updated 

I have question about size view through the browser.
Object size is too small for each element whos are in object.
And it cant be seen for user.

![98368395_190910885367868_5242807397872828416_n](https://user-images.githubusercontent.com/49090625/82425468-d8187c80-9a86-11ea-96f2-90a62c23692d.jpg)

Best regards,
Grzegorz Grodzki

**Comment by mediassarQlikBranch** [comment]
There is a mobile height setting to this one. Location of the parameter changed on 2.0.11
