### ISSUE TITLE
Can not upload extension to Qlik Cloud Extensions

### ISSUE THREAD

**Issue by newmans99** [mediassarQlikBranch/SimpleFieldSelect#35]
Because the ./dist/*.zip has zip files, which are not supported by Qlik Cloud this extension can not be uploaded to Qlik Cloud. I would like to recommend that these files be removed from the Extension ZIP file or that historical distributions be managed to github's version control instead.

**Comment by mediassarQlikBranch** [comment]
Thanks for pointing this out! I'll try to educate myself with Github. :) Also you could use latest zip file to install the extension
