### ISSUE TITLE
SimpleFieldSelect on Qlik Saas

### ISSUE THREAD

**Issue by adamgroenbeck** [mediassarQlikBranch/SimpleFieldSelect#38]
Hello,

It seems that the extension is now working properly on Qlik SaaS. When adding version 2.0.2, it says invalid extension when adding it. 2.0.3 cannot be uploaded.

Verseion 2.0.0 seems to be working :-)

**Comment by mediassarQlikBranch** [comment]
Could you be more specific what kind of error you get? Works for me. You should use zip files from dist folder.. that could be one thing maybe.
