### ISSUE TITLE
Qlik Checkbox search not filtering

### ISSUE THREAD

**Issue by DaneLooman** [mediassarQlikBranch/SimpleFieldSelect#41]
Searching using the hourglass icon does not filter the options correctly. Attached is an image showcasing the problem. 
<img width="326" alt="Screen Shot 2021-03-15 at 11 47 00 AM" src="https://user-images.githubusercontent.com/38257105/111181364-47b2a780-8584-11eb-840b-e76a81625275.png">

**Comment by mediassarQlikBranch** [comment]
Hi, thanks for pointing this out. Fixed in 2.0.9
