### ISSUE TITLE
SimpleFieldSelect freezes Qlik Sense custom sheets when clearing select2 dropdown

### ISSUE THREAD

**Issue by vbakke** [mediassarQlikBranch/SimpleFieldSelect#42]
On a custom sized sense sheet (and presumably) an extended sheet, the scroll bar of the sense sheet becomes frozen after clearing a selection.

**Comment by vbakke** [comment]
I see that the select2.min.js is attaching a scroll event handler on the body tag. Making scrolling impossible.
![image](https://user-images.githubusercontent.com/4437745/111349118-25eb1a80-8681-11eb-8466-cb72c015dadd.png)


By adding two `console.log`s in the select2's `_detachPositioningHandler()` and `_attachPositioningHandler()` I see that it is detaching before attaching.
```
checkin default selection, selected: 1
SimpleFieldSelect-dev.js:1880 init select2
select2.min.js:1 Detach: 0 DIV.sfsc.sfLjLmSu
select2.min.js:1 Detach: 1 DIV.sfsdiv
select2.min.js:1 Detach: 2 DIV.ng-scope
select2.min.js:1 Detach: 3 DIV.qv-object-content.ng-isolate-scope
select2.min.js:1 Detach: 4 DIV.qv-object-content-container
select2.min.js:1 Detach: 5 DIV.qv-inner-object.no-titles
select2.min.js:1 Detach: 6 ARTICLE.qv-object.qvt-visualization qv-layout-xsmall qv-object-SimpleFieldSelect-dev
select2.min.js:1 Detach: 7 DIV.cell-content.qv-object-wrapper ng-scope ng-isolate-scope
select2.min.js:1 Detach: 8 DIV.object-wrapper
select2.min.js:1 Detach: 9 DIV.object-and-panel-wrapper
select2.min.js:1 Detach: 10 DIV.cell.qv-gridcell qvt-gridcell ng-scope qv-gridcell-acc-focus
select2.min.js:1 Detach: 11 DIV.ng-isolate-scope
select2.min.js:1 Detach: 12 DIV.qvt-sheet.qv-panel-sheet ng-scope ng-isolate-scope qv-custom-size
select2.min.js:1 Detach: 13 DIV.qv-panel-content.flex-row
select2.min.js:1 Detach: 14 DIV.qv-panel.qv-panel-stage borderbox ng-scope
SimpleFieldSelect-dev.js:1763 select change action
SimpleFieldSelect-dev.js:371 set value to index 1
SimpleFieldSelect-dev.js:371 set value to index NaN
select2.min.js:1 Attach: 0 DIV.sfsc.sfLjLmSu
select2.min.js:1 Attach: 1 DIV.sfsdiv
select2.min.js:1 Attach: 2 DIV.ng-scope
select2.min.js:1 Attach: 3 DIV.qv-object-content.ng-isolate-scope
select2.min.js:1 Attach: 4 DIV.qv-object-content-container
select2.min.js:1 Attach: 5 DIV.qv-inner-object.no-titles
select2.min.js:1 Attach: 6 ARTICLE.qv-object.qvt-visualization qv-layout-xsmall qv-object-SimpleFieldSelect-dev
select2.min.js:1 Attach: 7 DIV.cell-content.qv-object-wrapper ng-scope ng-isolate-scope
select2.min.js:1 Attach: 8 DIV.object-wrapper
select2.min.js:1 Attach: 9 DIV.object-and-panel-wrapper
select2.min.js:1 Attach: 10 DIV.cell.qv-gridcell qvt-gridcell ng-scope qv-gridcell-acc-focus
select2.min.js:1 Attach: 11 DIV.ng-isolate-scope
select2.min.js:1 Attach: 12 DIV.qvt-sheet.qv-panel-sheet ng-scope ng-isolate-scope qv-custom-size
select2.min.js:1 Attach: 13 DIV.qv-panel-content.flex-row
select2.min.js:1 Attach: 14 DIV.qv-panel.qv-panel-stage borderbox ng-scope
select2.min.js:1 Attach: 15 BODY.qv-client.cust-card udirqlik-iframe cust-fonter qv-sheet-enabled 
```
It also goes way beyond the scope of the dropdown extension itself.

**Comment by vbakke** [comment]
Not sure if how you handle bugs or changes to the `select2.min.js` file, @mediassarQlikBranch. 

But my "fix" was to change:
`this.$container.parents().filter(b.hasScroll)`
into
`this.$container.parentsUntil('article').filter(b.hasScroll)`
in the two above functions.

I can make you a pull request. But maybe there are other or better solutions to this.  I don't know select2 that well.


Cheers,
Vegard :)

**Comment by vbakke** [comment]
Sidenote: 
Also in `select2.min.js` (just below the code I am referring to above) I have also changed the `_positionDropdown()`so that the dropdown is not "floating" with a gap between itself and the select box.

The fix was just to change:
`this.$container.outerHeight(!1)`
to
`this.$container.find('.select2-selection').outerHeight(!1)`
in two places.

**Comment by mediassarQlikBranch** [comment]
Thanks! I made changes to select2 library as you suggested.  Version 2.0.10
