### ISSUE TITLE
Is there a way to limit the length of a text input?

### ISSUE THREAD

**Issue by EliGohar85** [mediassarQlikBranch/SimpleFieldSelect#48]
Hi

Thanks for the great extension!
I created an input text (type = number) and wanted to know if there's a way to limit the user's input. Currently it accepts unlimited numbers:
![image](https://user-images.githubusercontent.com/64904978/133035222-6ca25256-48fe-4fb1-905b-915623a6c8bc.png)
I want to limit it (max length) to be maximum 5 digits.
I tried to update your js code by adding maxlength attribute but it didn't help.

Thanks.
Eli.

**Comment by mediassarQlikBranch** [comment]
Hi

you should be able to do this with there settings:
![kuva](https://user-images.githubusercontent.com/30590553/141127762-e8d78593-6c31-4f5d-8097-b8845abd2128.png)
Or are those enough?

**Comment by mediassarQlikBranch** [comment]
And now there is also extra parameter with 2.0.13 version. It allows you to add for example size="2" attribute to input element

**Comment by EliGohar85** [comment]
Hi @mediassarQlikBranch 
I tried the new version of 2.0.13. I added the attribute of size = 2 
![image](https://user-images.githubusercontent.com/64904978/141673023-898e702c-f71b-4487-8c56-d0dfcae86d5f.png)

I also verified it was added in the DOM:
![image](https://user-images.githubusercontent.com/64904978/141673030-813815cc-d78e-4c2f-bb1f-c74ec00b4698.png)

But I am still able to type inputs with more than 2 digits...
![image](https://user-images.githubusercontent.com/64904978/141673058-49804080-cfc0-4074-b1fc-81130fb2dae3.png)

Any idea why?
