### ISSUE TITLE
"Text on mouse hover" not working for Dropdown/select2

### ISSUE THREAD

**Issue by pepitolanda** [mediassarQlikBranch/SimpleFieldSelect#49]
Hi, I'm trying to use the mouse hover text and it doesn't work. At least for Dropdown/Select2 where I tried it.
Instead, it displays "x values selected" (dropdown) or the actual value selected (Select2)

I think issue is that Title property from HTML DIV is correctly set with the expected text. However, the child html item also has a Title property assigned (with the quantity of values selected). Thus, this last value is shown instead of the expected value set in the properties panel.

**Comment by mediassarQlikBranch** [comment]
Fixed for dropdown in 2.1.1. The hover text comes with selected count.
It is more complicated for select2 because the plugin itself generates title for every option in the list.

**Comment by pepitolanda** [comment]
Hi

Thanks for taking care of it and fix it! :)
Regarding select2, what I have done is to do some css changes to show the title over the combo box only when the user hovers over it. It works on my case because title is not display due to space limitations. I need to use the tooltip to show more info. Thus, I was able to convert the title into a tooltip.

This is part of the css I'm using to achieve it (in case it is useful to someone).

`

/* Combo box: Set width and height for combo box with QS object SimpleField under "select2' option */
.qv-object-SimpleFieldSelect .select2-container {
	width: 100% !important;
	height: 60%;
}

/*Format for selectors without a title. 
When user hover title is shown (fix until tooltip works fine for this QS object)*/
[tid="HEjuHYw"] .qv-object-SimpleFieldSelect .inlinelabeldiv {
	visibility: hidden;
	width: 80%;
        height: calc(70% - 2px);		/* 70% is the height given to combobox and 2px is the border */
	/* Position the tooltip */
    position: absolute;
	/* allow click over object behind (drop down)*/
	pointer-events: none;
	/* Make sure it shows up on top of the combobox object */
	z-index: 10;
  }


/* Format for selectors without a title. 
Make title/tooltip visible when hovering*/
[tid="HEjuHYw"]:hover .qv-object-SimpleFieldSelect .inlinelabeldiv {
	visibility: visible;
}


/* Combo box WITHOUT title: Set height for combo box with QS object SimpleField under "select2' option */
[tid="HEjuHYw"] .qv-object-SimpleFieldSelect .select2-container {
	height: 100%;
}


/* Combo box WITHOUT title: Set height for combo box with QS object SimpleField under "select2' option */
[tid="HEjuHYw"] .sfsdiv {
	height: 70% !important;
}`
