### ISSUE TITLE
Add actions to extension properties

### ISSUE THREAD

**Issue by sbrusse** [mediassarQlikBranch/SimpleFieldSelect#5]
Would be great to be able to set multiple actions in the extension, for instance to clear a field or select a field value.

**Comment by Enriquema** [comment]
This is on going in [Pull request](https://github.com/mediassarQlikBranch/SimpleFieldSelect/pull/12) for select2. You could download the code forked from [Enriquema/SimpleFieldSelect](https://github.com/Enriquema/SimpleFieldSelect)

**Comment by Enriquema** [comment]
This is on going in #12 for select2. You could download the code forked from [Enriquema/SimpleFieldSelect](https://github.com/Enriquema/SimpleFieldSelect
