### ISSUE TITLE
Date Picker selector not working under may 2022 and next versions

### ISSUE THREAD

**Issue by antritz** [mediassarQlikBranch/SimpleFieldSelect#51]
Version 2.1.5 has been installed on premise on a server having Qlik Sense Entrerprise May 2022 (also on August 2022 I have the same behaviour).
I have a simple field selector using a variable bound to a date picker 
When running, the html has been built correcty but when added to $element

$element.html( html );

the subsequent statement
var datepickElement = $element.find( '.pickdate' );
does not decorate the single elements with id and hasDatepicker class
 
ie.
input#dp1662133755069.sfe.pickdate.hasDatepicker
in QS version February 2022 patch 2

input.sfe.pickdate
in QS verson MAy 2022

The [...] button is not rendered and left click in field does not show the date picker

**Comment by mediassarQlikBranch** [comment]
Hi, it seems that the jqueryUI library has been removed from lates Cloud and server versions of Qlik. Desktop version still has it. As a workaround we'll create a version which replaces the jqueryUI datepicker component with native HTML date field.
If you have any idea of a simpl, working datepicker library (best of course if included with Qlik itself) let us know.

**Comment by npapapicco** [comment]
Hi, when do you think a new version resolving the issue will be available?
Regards

**Comment by mediassarQlikBranch** [comment]
Fixed so that jQueryUI datepicker component has been added to SFS. The library was removed from Qlik.
Desktop version of Qlik still has the jQueryUI library...
