### ISSUE TITLE
no longer working for Cloud?

### ISSUE THREAD

**Issue by gt-nyc** [mediassarQlikBranch/SimpleFieldSelect#55]
Hello,
I just tried the 3 zip distros on the SAAS environment . 
- SimpleFieldSelect2.1.9.zip won't upload at all.
- the 2 other latest versions will upload successfully but the widget looks broken: some CSS or JS is not loading properly so the buttons don't change colors when we click to select a value. Some widgets are not working at all, like the horizontal qliksense list that shows the LI html list as vertical values without any styling.
thanks in advance for your help.

**Comment by mediassarQlikBranch** [comment]
Yes, for some reason the cloud environment doesn't load one of the CSS files. This is maybe related to this add of purify functionality. We are working on this issue. 2.1.8 version works. (Qlik Cloud seems to have some bugs also related to extension uploads)
