### ISSUE TITLE
Suggested changes for proper Associative Styling

### ISSUE THREAD

**Issue by leematthewshome** [mediassarQlikBranch/SimpleFieldSelect#6]
I wanted to use your extension for a demo application, but it doesnt use the right green, white, grey, light grey styling. I propose a couple of changes to enable this (note that I have only made these changes for button display):

1. In scoped-bootstrap.css add the following below .btn-default

/* =========== Begin Qlik Specific Colors =========== */
.bootstrap_inside .btn-notassociated {
    color: #ffffff;
    background-color: #a9a9a9;
    border-color: #ccc;
}

.bootstrap_inside .btn-alternative {
    color: #333;
    background-color: #dddddd;
    border-color: #ccc;
}
/* =========== End Qlik Specific Colors =========== */

2. In SenseFieldUI.js make the following changes to the eachDataRow function for buttons:

			 //if (row[0].qState === 'X') { var dis = 'disabled'; } else { var dis = ''; };
			var dis = '';
                        if (row[0].qState === 'S') {
                            var active = 'btn-' + vars.btnColor;
                            tempId[n].push(row[0].qElemNumber);
                        } 
			else if (row[0].qState === 'A'){
				var active = 'btn-alternative';
			}
			else if (row[0].qState === 'X'){
				var active = 'btn-notassociated';
			}
			else { var active = 'btn-default'; };

**Comment by mediassarQlikBranch** [comment]
Hi

are you sure that you posted this on correct extension? This extension doesn't use bootstrap anyway and file names are not familiar. :)
In SimpleFieldSelect extension, you can already set colors as you wish.

br Matti

**Comment by leematthewshome** [comment]
Oops. Sorry, yes should be another extension.
