### ISSUE TITLE
Add Horizontal Qlik Checkbox

### ISSUE THREAD

**Issue by Freighar** [mediassarQlikBranch/SimpleFieldSelect#7]
It would be great if this extension adds the option to display Horizontal Qlik Checkbox.

I tried to do it myself but i dont see the option on the Leonardo ui checkbox.

Thanks,

**Comment by mediassarQlikBranch** [comment]
You can use in Advanced CSS section -> Custom CSS for every element and set it to 
display:inline-block; 
Then you might want to add some padding also, like display:inline-block; padding-left:5px;
